### ISSUE TITLE
Please update document 

### ISSUE THREAD

**Issue by nk-nareshkumar** [QoboLtd/cakephp-cms#111]
Hi, 
Seems great job with the plugin, but seems some where help document is not clear.. we are not getting how to access the admin pages..
I tried with http://localhost/mycake/Articles/ but there was error with article controller missing..

Seems, its not a complete with help for a novice that how to setup from scratch and how to work with it.

**Comment by mamchenkov** [comment]
@nk-nareshkumar ,

yes, you are right.  The documentation is lacking quite a bit, as this plugin is a very fresh version.  We'll work on this in the next few days.

**Comment by nk-nareshkumar** [comment]
@mamchenkov i also drop email on your email id.. Also i am waiting for document to help here on GIT..
I spend my whole day to setup this but nothing working.. :)

**Comment by mamchenkov** [comment]
@nk-nareshkumar yes, I saw the email, but I prefer to have the issues here, so that we can keep track of them properly.

We've started working on the documentation update, but it's not finished yet.  The first update is in this PR #112 .  Please let me know if that works for you or if you need more information.

**Comment by nk-nareshkumar** [comment]
Hi there,

Thank you for this help..
i tried to install with new doc.. but seems some issue here , see in screen shot.

When i tried to visit this url to view site. http://localhost/cake3/cms/sites/view/google.com

More how can i add url and how can i add articles, category, content etc.. 
and why we creating sites ? even we have only one site to work with cms then why multiple site ?

![error missing helper](https://user-images.githubusercontent.com/2937132/28793657-56735436-7651-11e7-8d50-f1f9c8f2bb73.png)

Thanks,

**Comment by mamchenkov** [comment]
@nk-nareshkumar 

> i tried to install with new doc.. but seems some issue here , see in screen shot.

Thanks.  We'll add some more instructions in the next couple of days.  It's a bit tricky for us, as we don't use the plugin as standalone with vanilla CakePHP, but together with a whole bunch of other things.  But we'll isolate the instructions shortly.

> More how can i add url and how can i add articles, category, content etc..

Categories are built-in, so to add them you'd use a web interface, once the site is created, similar how you add articles and other content.

You can configure which types of content you want to support.  Have a look in `config/cms.php`.  We define a few things out of the box, but you can customize those to your liking.

> and why we creating sites ? even we have only one site to work with cms then why multiple site ?

Sites are an organizational unit for content.  We use them to organize different content together, like Documents, etc., as well as to give permissions.  We mostly use this plugin for Intranet-kind of setups, where each department in the company, for example, has its own internal site.  Whoever has access to the site, has access to view all categories and articles.

**Comment by mamchenkov** [comment]
@nk-nareshkumar 

Here are some documentation updates coming your way. :)

First of all, have a look at [this PR](https://github.com/QoboLtd/cakephp-utils/pull/50) from the Qobo/Utils plugin, which now covers the setup of the AdminLTE theme.

Secondly, have a look at PR #114 for additional instructions on the setup of the CMS plugin.

This is still not finished and needs more work (and maybe an easier setup process), but it should move you along the installation process quite a bit. :)

**Comment by nk-nareshkumar** [comment]
Hi, Thank you for your reply.

Just want to know, Should i install

**Comment by mamchenkov** [comment]
@nk-nareshkumar composer will install all required dependencies, so you don't need to worry about them.

**Comment by nk-nareshkumar** [comment]
@mamchenkov yes its working and installed.
More i want to know 
how can i add articles, content and page/post ?

I am not getting any url to add article, page, post
I tried to add article from http://localhost/cake3/cms/sites/view/google
but there is no any option to add article ..

**Comment by mamchenkov** [comment]
@nk-nareshkumar 

sorry for a delayed reply - it got a bit busy here in the office.  There is one last thing you need to do to get the content management controls.  It's an event listener - which we usually have our own to deal with things like permissions, etc.  But we'll add a default one to work for any installation later today.

Once that is done, you'll have the full functionality.  And yes, it will be much like WordPress.  We work a lot with WordPress too and love it.  But the CMS part of this plugin is of course much smaller and simpler than a full blown CMS developed by Open Source crowd for many years now. :)

Our content management functionality and interface was inspired by the WordPress' [P2 theme](https://p2theme.com/).  Just give us a few hours, and we'll push the update here.

Thanks.

**Comment by nk-nareshkumar** [comment]
@mamchenkov i appreciate. really appreciate.

**Comment by mamchenkov** [comment]
@nk-nareshkumar we've just released a new version of the plugin, that includes the default event listener for the content administration, as well as an updated README file which documents how to load it.

Can you please try it and let me know if it's finally working for you or if you need more instructions.

Thanks a lot for your patience. :)

**Comment by nk-nareshkumar** [comment]
Hi There , You did a awesome job.. i really like it.

Just want to share some feedback 

Readme suggestion: 
Just to share with user:

1. Add this in  " use Cake\Event\EventManager; " below.// config/bootstrap.php
use Cms\Event\View\SitesManageListener;
use Cake\Event\EventManager;
EventManager::instance()->on(new SitesManageListener());

2. to get better result implement the CakePHP3 Auth from here ' https://book.cakephp.org/3.0/en/tutorials-and-examples/blog-auth-example/auth.html' . Otherwise you can get some Cake Auth User errors.

**Comment by mamchenkov** [comment]
@nk-nareshkumar thank you so much for your feedback!

We are incorporating the updated instructions to the README (see PR #119), which will be merged and tagged in a new version today.

**Comment by mamchenkov** [comment]
@nk-nareshkumar we have just released [v6.5.1](https://github.com/QoboLtd/cakephp-cms/releases/tag/v6.5.1) of this plugin with all the updates to the README file.

Are you OK with us closing this issue now or do you need any more documentation?

**Comment by nk-nareshkumar** [comment]
Thanks.. i appreciate you did a great job.
closing the issue..
