### ISSUE TITLE
Support content in shortcodes

### ISSUE THREAD

**Issue by FinlayDaG33k** [QoboLtd/cakephp-cms#151]
Hii there,
I'm using your CMS, and was wondering if the shortcode helper could be updates so we can have "content" in the shortcode like this:

```
[img]https://via.placeholder.com/1920x1080[/img]
```

instead of:
```
[img src="https://via.placeholder.com/1920x1080"]
```
It would look a bit cleaner to write for editors in my opinion (and of course, it's more compatible with forum-style shortcodes you get from a lot of places like Imgur).

**Comment by mamchenkov** [comment]
Hi @FinlayDaG33k ,

glad to hear you found the plugin useful.

Our shortcode functionality is built after the WordPress shortcodes.  Can you provide an example of an Open Source system, which uses the shortcodes that you find more useful?  We'll look at the possibility of supporting multiple different parsers via the configuration.

**Comment by FinlayDaG33k** [comment]
Well, ehm... WordPress does :) 
This is how I write it in WordPress:
![code](https://i.imgur.com/c1MWv40.png)

And this is how it displays in the site itself:
![render](https://i.imgur.com/di6DCIA.png)

In the shortcode function I have writted this:
```php
function img_func($atts, $content = null){
  // Use some dark voodoo magic
}
```

`$atts` is all I get from the plugin at the moment (as intended):
```php
protected static function renderImg(array $params){
  // Use almost the same dark voodoo magic... but bake a cake while at it
}
```

so, if the shortcode "engine" get's updated for your cms, I would write:
```php
protected static function renderImg(array $params, string $content){
  // Updated voodoo magic
}
```

on the flip-note, this `$content` could also be added as an item to the `$params` instead (eg. `$paramgs['content']`.

**Comment by mamchenkov** [comment]
Hi @FinlayDaG33k ,

this makes sense.  We'll look into implementing this shortly.
Or you can send the PR to speed things up. ;)

Thanks.

**Comment by mamchenkov** [comment]
@FinlayDaG33k 

the PR has been merged and tagged.  Thanks for the contribution and apologies for the delay - we were a bit swarmed recently. :)
