### ISSUE TITLE
Compatibility with cake 3.6

### ISSUE THREAD

**Issue by matibaski** [QoboLtd/cakephp-cms#156]
Not technically an issue, but are you planning on a new release for the newest cake version?

**Comment by mamchenkov** [comment]
Hi,

yup.  Within next month or so, we are dropping support for PHP 5.6 and moving to PHP 7.1.  Once that is done, we are moving to CakePHP 3.6.

**Comment by matibaski** [comment]
That was, I think, the fastest answer I ever had on GitHub. Thanks in advance.
